# Generated by Django 4.2.3 on 2024-01-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
